### ISSUE TITLE
Redis Enterprise Operator failing on OpenShift 4.3

### ISSUE THREAD

**Issue by davivcgarcia** [RedisLabs/redis-enterprise-k8s-docs#117]
I'm trying to deploy the operator directly from the Operator Hub Catalog but looks like the required SecurityContextConstraint (SCC) is not being automatically created. Checking the events in the namespace where the operator is being deployed, we see this error:

```
63s         Warning   FailedCreate           statefulset/rec                                             create Pod rec-0 in StatefulSet rec failed error: pods "rec-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000540000, 1000549999] capabilities.add: Invalid value: "SYS_RESOURCE": capability may not be added spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000540000, 1000549999] capabilities.add: Invalid value: "SYS_RESOURCE": capability may not be added]
```

Trying using the manual procedure described on this repo, looks like the LimitRange created prohibits the StatefulSet creating:

```
3s          Warning   FailedCreate           statefulset/redis-enterprise-cluster-01                                        create Pod redis-enterprise-cluster-01-0 in StatefulSet redis-enterprise-cluster-01 failed error: pods "redis-enterprise-cluster-01-0" is forbidden: [maximum cpu usage per Container is 2, but limit is 4, maximum cpu usage per Pod is 2, but limit is 4100m]
```

Checking the LimitRange resource create, I see this (which explains the previous error):

```
 $ oc describe limitrange
Name:       demo-redisenterprise-manual-core-resource-limits
Namespace:  demo-redisenterprise-manual
Type        Resource  Min  Max   Default Request  Default Limit  Max Limit/Request Ratio
----        --------  ---  ---   ---------------  -------------  -----------------------
Container   cpu       -    2     50m              500m           -
Container   memory    -    6Gi   256Mi            1536Mi         -
Pod         cpu       -    2     -                -              -
Pod         memory    -    12Gi  -                -              -
```

I think this is a side effect of the RedisEnterpriseCluster I created:

```
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: redis-enterprise-cluster-01
  namespace: demo-redisenterprise-manual
spec:
  createServiceAccount: true
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: gp2
    volumeSize: 20Gi
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    repository: redislabs/redis
    versionTag: 5.4.14-31.rhel7-openshift
  redisEnterpriseNodeResources:
    limits:
      cpu: "4"
      memory: 4Gi
    requests:
      cpu: "2"     #<-- I changed to 2 instead of 4
      memory: 4Gi
  serviceAccountName: redis-enterprise-cluster-01
  serviceBrokerSpec:
    enabled: false
    persistentSpec:
      enabled: null
      storageClassName: ""
      volumeSize: "0"
  servicesRiggerSpec:
    databaseServiceType: cluster_ip,headless
    serviceNaming: bdb_name
  uiServiceType: LoadBalancer
  username: xxx@xxx.com
```

Any chance of the operator setting the wrong LimitRange based on redisEnterpriseNodeResources values?
