### ISSUE TITLE
Where can I find details or examples for creating a real RedisEnterpriseDatabase resource?

### ISSUE THREAD

**Issue by grtrout** [RedisLabs/redis-enterprise-k8s-docs#189]
I was hoping that I could create a database in the UI and it would create a RedisEnterpriseDatabase resource that I could learn from, but creating the database in the UI does not create a RedisEnterpriseDatabase resource at all. The examples for RedisEnterpriseDatabase have basically nothing outside of the memorySize specified.

So, where can I find examples of a RedisEnterpriseDatabase  resource where things like replication, shards, eviction policy, etc. are specified?

Thanks!

**Comment by laurentdroin** [comment]
Hi,

Indeed, creating a database in the UI will not create a corresponding REDB Kubernetes resource (the Redis Enterprise Cluster by itself not being aware it is running in a Kubernetes environment).
Note that when a database is created as a REDB resource, the manifest for that resource is the source of truth, and modifications you may make to the database in the UI will be reverted as the REDB controller will constantly try to reconcile the REDB resource specification with the real world. 

You can find all the REDB supported properties here: https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/redis_enterprise_database_api.md#redisenterprisedatabasespec

Here is a small example of a REDB definition that makes use of some of these properties:

```
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: my-custom-db
spec:
  memorySize: 100MB
  replication: true
  persistence: snapshotEvery1Hour
  shardCount: 2
  evictionPolicy: allkeys-lru
```

I hope this will help.

Cheers,

Laurent.

**Comment by grtrout** [comment]
@laurentdroin  Thank you - that is very helpful.

A few comments:
- I wish the Redis Enterprise Cluster was aware that it was running in a K8s environment. I think the experience would be improved.
- Even when I create a REDB resource that is ultimately "bad," it still gets created. The only way I know it didn't work is due to its relevant services never being created and/or it not appearing in the UI.
  -  E.g.: if I add `.spec.backup: {} ` the REDB is created, but nothing else happens.
- No events ever seem to get created in my namespace, whether to indicate success or failure.
- I should be able to create the REDB in a different namespace than where the operator itself is deployed. There seems to be no way to do this.

Finally, and this is just in case it helps anyone else, here is the YAML I settled on using:

```
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redb-db1
spec:
  memorySize: 2GB
  alertSettings:
    DbAlertsSettings:
      bdb_size:
        enabled: true
        threshold: "90"
  defaultUser: false
  evictionPolicy: allkeys-lru
  shardCount: 4
  persistence: disabled
  rackAware: false
  clientAuthenticationCertificates: []
  databaseSecretName: "redb-test-secret"
  modulesList: []
  ossCluster: false
  proxyPolicy: single
  redisEnterpriseCluster:
    name: rec-test
  replicaSources: []
  replication: true
  rolesPermissions: []
  tlsMode: disabled
```

**Comment by laurentdroin** [comment]
Hi @grtrout 

There is an admission controller that you can configure and that should help block the REDB creation if the corresponding database cannot be created. The admission controller is now deployed as part of the Operator deployment (in its own container).
See step 5 of https://github.com/RedisLabs/redis-enterprise-k8s-docs#installation and also https://github.com/RedisLabs/redis-enterprise-k8s-docs/tree/master/admission

There is also a way to deploy a REDB resource in a different namespace (which we call "consumer" namespace).
See https://github.com/RedisLabs/redis-enterprise-k8s-docs/tree/master/multi-namespace-redb

Hope this is helpful.

Laurent.

**Comment by grtrout** [comment]
@laurentdroin Excellent! I will check into both the admission controller and the consumer namespace strategy. Thanks for your help.

**Comment by grtrout** [comment]
@laurentdroin - is it possible to configure a RedisEnterpriseDatabase using the RedisEnterpriseDatabaseSpec and **not require auth**?

**Comment by laurentdroin** [comment]
@grtrout - Not directly, but you should be able to achieve this by creating a secret with an empty password **first** and then specifying that secret in the REDB manifest before the REDB is created.

Something like:
`kubectl create secret generic my-password --from-literal=password=''`

and then:

```yaml
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: my-db
spec:
  databaseSecretName: my-password
```
I hope this helps.

Laurent.
