### ISSUE TITLE
Disable persistent does not work

### ISSUE THREAD

**Issue by soroshsabz** [RedisLabs/redis-enterprise-k8s-docs#212]
ITNOA

I try to create `redis enterprise cluster` with below declaration

```
apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "harbor-cluster"
spec:
  nodes: 3
  persistentSpec:
    enabled: false
  redisEnterpriseNodeResources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi
```

But my problem is even I set `presistentSpec` to false, I see `kubectl get pvc` show redis try to claim `pv` and my bootstrapping of my pods is failed.

my question is how to resolve it?
