### ISSUE TITLE
Deployment of Redis cluster failing when using Operator with Cluster Scope 

### ISSUE THREAD

**Issue by Dimss** [RedisLabs/redis-enterprise-k8s-docs#67]
I'm trying to deploy Redis Operator in [cluster scope](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md). 
Here is my Operator `Deployment`, `rbac` , `crd` and `cr` manifests with required patches for deploying an Redis Operator in Cluster Scope. 

### `Deployment`
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-enterprise-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-enterprise-operator
  template:
    metadata:
      labels:
        name: redis-enterprise-operator
    spec:
      serviceAccount: redis-enterprise-operator
      containers:
        - name: redis-enterprise-operator
          image: redislabs/operator:5.4.6-1086
          securityContext:
            runAsUser: 1001
          command:
          - redis-enterprise-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
```

### `RBAC`
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator
rules:
- apiGroups: ["rbac.authorization.k8s.io", ""]
  resources: ["roles", "serviceaccounts", "rolebindings"]
  verbs: ["*"]
- apiGroups:
  - app.redislabs.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["create", "delete", "get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "get" , "update", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get" , "update"]

# needed rbac rules for services controller
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "update", "patch", "create", "delete"]
- apiGroups:
  - route.openshift.io
  resources: ["routes", "routes/custom-host"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  resourceNames:
  - redis-enterprise-psp
  verbs:
  - use
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["*"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: redis-enterprise-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator
subjects:
- kind: ServiceAccount
  name: redis-enterprise-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: redis-enterprise-operator
  apiGroup: rbac.authorization.k8s.io
```

### `CRD`
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redisenterpriseclusters.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: RedisEnterpriseCluster
    listKind: RedisEnterpriseClusterList
    plural: redisenterpriseclusters
    singular: redisenterprisecluster
    shortNames:
    - rec
  scope: Cluster
  version: v1alpha1
```

### `CR`
```
apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: "gp2" # ! edit according to infrastructure
  uiServiceType: LoadBalancer
  username: "admin@acme.com"
  redisEnterpriseNodeResources:
    limits:
      cpu: "4000m"
      memory: 4Gi
    requests:
      cpu: "4000m"
      memory: 4Gi
```
After creating `CR`, e.g: `kubectl apply -f redis-enterprise-cluster.yaml` none of the requirement objects are created, and in operator log i'm getting the following error: 
```
{
  "level": "error",
  "ts": 1567507320.950409,
  "logger": "redis_enterprise",
  "msg": "Failed to create service account",
  "error": "an empty namespace may not be set during creation",
  "stacktrace": "github.com/RedisLabs/redis-enterprise-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/RedisLabs/redis-enterprise-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/RedisLabs/redis-enterprise-operator/pkg/redis_enterprise.(*REResourcesHandler).DeployRedisEnterprise\n\t/go/src/github.com/RedisLabs/redis-enterprise-operator/pkg/redis_enterprise/resources.go:949\ngithub.com/RedisLabs/redis-enterprise-operator/pkg/controller/redisenterprisecluster.(*ReconcileRedisEnterpriseCluster).Reconcile\n\t/go/src/github.com/RedisLabs/redis-enterprise-operator/pkg/controller/redisenterprisecluster/redisenterprisecluster_controller.go:132\ngithub.com/RedisLabs/redis-enterprise-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/RedisLabs/redis-enterprise-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/RedisLabs/redis-enterprise-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/RedisLabs/redis-enterprise-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/RedisLabs/redis-enterprise-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/RedisLabs/redis-enterprise-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/RedisLabs/redis-enterprise-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/RedisLabs/redis-enterprise-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/RedisLabs/redis-enterprise-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/RedisLabs/redis-enterprise-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}
```

Is by design Redis Enterprise Operator supposed to support cluster scope deployment? 
If yes, how I should deploy it? 
If no, is there any way to patch your Operator to add support for cluster scope deployments (is it Open Source)?
